### ISSUE TITLE
Tag a release :)

### ISSUE THREAD

**Issue by AdrieanKhisbe** [gaudecker/draft-mode#3]
@gaudecker 
Could you tag a commit so that your module get build on melpa-stable.

:smiley:

**Comment by gaudecker** [comment]
Oh yeah, sure. I'll get it done tomorrow! <3

**Comment by AdrieanKhisbe** [comment]
great! :)

**Comment by gaudecker** [comment]
Tagged latest version as `0.1.1`.

**Comment by AdrieanKhisbe** [comment]
cool :D
